export const Random = [
    "Aardvark",
    "Abyssinian",
    "Adelie Penguin",
    "Affenpinscher",
    "Afghan Hound",
    "African Bullfrog",
    "African Bush Elephant",
    "African Civet",
    "African Clawed Frog",
    "African Forest Elephant",
    "African Palm Civet",
    "African Penguin",
    "African Tree Toad",
    "African Wild Dog",
    "Ainu",
    "Airedale Terrier",
    "Airedoodle",
    "Akbash",
    "Akita",
    "Akita Shepherd",
    "Alabai",
    "Alaskan Husky",
    "Alaskan Malamute",
    "Alaskan Shepherd",
    "Albacore Tuna",
    "Albatross",
    "Aldabra Giant Tortoise",
    "Alligator",
    "Alligator Gar",
    "Alpaca",
    "Alpine Dachsbracke",
    "Alpine Goat",
    "Alusky",
    "Amazon River Dolphin (Pink Dolphin)",
    "American Alsatian",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless Terrier",
    "American Pit Bull Terrier",
    "American Pygmy Goat",
    "American Staffordshire Terrier",
    "American Toad",
    "American Water Spaniel",
    "Amur Leopard",
    "Anatolian Shepherd Dog",
    "Anchovies",
    "Angelfish",
    "Angora Goat",
    "Ant",
    "Anteater",
    "Antelope",
    "Appenzeller Dog",
    "Apple Head Chihuahua",
    "Arapaima",
    "Arctic Fox",
    "Arctic Hare",
    "Arctic Wolf",
    "Armadillo",
    "Asian Elephant",
    "Asian Giant Hornet",
    "Asian Palm Civet",
    "Asiatic Black Bear",
    "Aurochs",
    "Aussiedoodle",
    "Aussiedor",
    "Australian Bulldog",
    "Australian Cattle Dog",
    "Australian Kelpie Dog",
    "Australian Labradoodle",
    "Australian Mist",
    "Australian Retriever",
    "Australian Shepherd",
    "Australian Terrier",
    "Avocet",
    "Axolotl",
    "Aye Aye",
   " Bactrian Camel",
    "Badger",
    "Balinese",
    "Banded Palm Civet",
    "Bandicoot",
    "Banjo Catfish",
    "Barb",
    "Barn Owl",
    "Barnacle",
    "Barracuda",
    "Barramundi Fish",
    "Barred Owl",
    "Basenji Dog",
    "Basking Shark",
    "Bassador",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Bassetoodle",
    "Bat",
    "Bavarian Mountain Hound",
    "Bea - Tzu",
    "Beagador",
    "Beagle",
    "Beagle Shepherd",
    "Beaglier",
    "Bear",
    "Bearded Collie",
    "Bearded Dragon",
    "Beaski",
    "Beaver",
    "Bedlington Terrier",
    "Beetle",
    "Belgian Shepherd",
    "Beluga Sturgeon",
    "Bengal Tiger",
    "Bergamasco",
    "Bernedoodle",
    "Bernese Mountain Dog",
    "Bernese Shepherd",
    "Bichir",
   " Bichon Frise",
   " Bichpoo",
  "  Biewer Terrier",
   " Bighorn Sheep",
   " Bilby",
   " Binturong",
   " Bird",
   " Bird Of Paradise",
   " Birman",
   " Bison",
   " Black Marlin",
   " Black Rhinoceros",
   " Black Russian Terrier",
   " Black Wasp",
   " Black Widow Spider",
   " Black - Footed Ferret",
   " Baboon",
   " Blister Beetle",
   " Blobfish",
   " Bloodhound",
   " Blue grosbeak",
   " Blue Iguana",
   " Blue Jay",
   " Blue Lacy Dog",
   " Blue Shark",
   " Blue Whale",
   " Bluefin Tuna",
   " Bluetick Coonhound",
   " Bobcat",
   " Boggle",
   " Boglen Terrier",
   " Bolognese Dog",
   " Bombay",
   " Bonito Fish",
   " Bonnethead Shark",
   " Bonobo",
   " Booby",
   " Borador",
   " Border Collie",
   " Borkie",
   " Bornean Orang - utan",
   " Borneo Elephant",
   " Boston Terrier",
   " Bottlenose Dolphin",
   " Bowfin",
   " Bowhead Whale",
   " Box Turtle",
   " Boxador",
   " Boxer Dog",
   " Boxerdoodle",
    "Boxsky",
  "  Boxweiler",
   " Boykin Spaniel",
  "  Brazilian Terrier",
   " British Timber",
   " Brittany",
   " Brown Bear",
   " Brown Hyena",
   " Bongo",
   " Budgerigar",
   " Buffalo",
   " Bull Shark",
   " Bull Terrier",
    "Bulldog",
    "Bullfrog",
   " Bullmastiff",
   " Bumblebee",
   " Burmese",
    "Burmese Python",
   " Burrowing Frog",
    "Bush Baby",
    "Butterfly",
    "Border Terrier",
    "Beabull",
    "Butterfly Fish",
    "Acacia",
    "Aconite",
    "African Daisy",
    "Agapanthus",
    "Ageratum",
    "Alchemilla",
    "Allium",
    "Alstroemeria",
    "Alyssum",
    "Amaranthus",
    "Amaryllis",
    "Anemone",
    "Anise Hyssop",
    "Armeria Maritima",
    "Aster",
    "Azalea",
    "Bachelor’s Button",
    "Balloon Flower",
    "Ballota",
    "Bee Balm",
    "Begonia",
    "Bellflower",
    "Bergamot",
    "Bergenia",
    "Billbergia",
    "Black-eyed Susan",
    "Blanket Flower",
    "Blazing Star",
    "Bleeding Heart",
    "Bletilla",
    "Bluestar Flower",
    "Bluebonnets",
    "Blue-eyed Grass",
    "Borage",
    "Bottlebrush",
    "Bouvardia",
    "Brachyscome",
    "Brassica",
    "Broom",
    "Buttercup",
    "Butterfly Bush",
    "Calceolaria",
    "California Poppy",
    "Calendula",
    "Calla Lily",
    "Camellia",
    "Canna Lily"
];
